create database dbms_project;
show databases;
use dbms_project;

show tables
CREATE TABLE TRADERS (
TRADER_ID	VARCHAR(10) PRIMARY KEY,
TRADER_NAME	VARCHAR(20) NOT NULL,
TRADER_CO_NUMBER NUMERIC(10),
TRADER_TYPE	VARCHAR(20) NOT NULL,
TRADER_LOCATION	VARCHAR(20) NOT NULL);

CREATE TABLE EMPLOYEEES (
EMP_ID		NUMERIC(10) PRIMARY KEY,
EMP_COMPANY_NAME	VARCHAR(20),
EMP_LNAME	VARCHAR(15) NOT NULL,
EMP_FNAME	VARCHAR(15) NOT NULL,
EMP_PHONE	VARCHAR(10) NOT NULL,
EMP_SALARY	NUMERIC(20));
ALTER TABLE EMPLOYEEES RENAME TO EMPLOYYEE;

CREATE TABLE FACTORYY (
FACTORY_ID 	NUMERIC(10) PRIMARY KEY,
FACTORY_NAME VARCHAR(50) NOT NULL,
FACTORY_CO_NUMBER	NUMERIC(10),
FACTORY_STOCK	NUMERIC(50),
FACTORY_LOCATION	VARCHAR(20),
FACTORY_OWNER VARCHAR(20) );
ALTER TABLE FACTORYY RENAME TO FACTORY;

CREATE TABLE ITEMSSSSSS (
ITEM_ID	NUMERIC(10) PRIMARY KEY,
ITEM_AVAILABILITY	VARCHAR(50),
ITEM_WEIGHT	NUMERIC(50),
ITEM_TYPE	VARCHAR(50) );
ALTER TABLE ITEMSSSSSS RENAME TO ITEM;

CREATE TABLE DRIVERS (
DRIVER_ID	NUMERIC(10) PRIMARY KEY,
DRIVER_CO_NUMBER	NUMERIC(10),
DRIVER_SALARY	NUMERIC(50) ,
DRIVER_NAME	VARCHAR(20) );

CREATE TABLE BILLS (
GSTIN 	NUMERIC PRIMARY KEY,
E_INVOICE_NUMBER NUMERIC NOT NULL,
BILLING_NAME	VARCHAR(20),
TOTAL_AMOUNT NUMERIC(50));

CREATE TABLE DEPENDENTSS(
EMP_ID		NUMERIC(10),
DEPENDENT_NAME VARCHAR(20) PRIMARY KEY,
DEPENDENT_NUMBER NUMERIC(10),
INSURANCE NUMERIC,
CONSTRAINT 	DEPENDENT FOREIGN KEY(EMP_ID) REFERENCES EMPLOYYEE(EMP_ID));
ALTER TABLE DEPENDENTSS RENAME TO DEPENDENT;

CREATE TABLE LOADERSS (
DRIVER_ID	NUMERIC(10),
LOADER_ID NUMERIC(20) PRIMARY KEY,
LOADER_NUMBER VARCHAR(20),
START_LOC VARCHAR(20) NOT NULL,
END_LOC VARCHAR(20),
TOTAL_DAYS_TAKEN NUMERIC(20),
CONSTRAINT 	LOADER FOREIGN KEY(DRIVER_ID) REFERENCES DRIVERS(DRIVER_ID));
ALTER TABLE LOADERSS RENAME TO LOADER;

show tables
